module.exports = {
  extends: ["eslint:recommended"],
  rules: {
    camelcase: "error",
    curly: ["error", "multi-line"],
    "default-case": ["error", { commentPattern: "^no default$" }],
    "default-param-last": "error",
    eqeqeq: "error",
    "no-multi-assign": ["error"],
    "no-console": "error",
    "no-shadow": "error",
    "no-use-before-define": "error",
    "no-eval": "error",
    "no-alert": "warn",
    "no-useless-concat": "error",
    "no-useless-rename": "error",
    "no-implied-eval": "error",
    "no-loop-func": "error",
    "no-await-in-loop": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": ["error", { includeExports: true }],
    "no-new-native-nonconstructor": "error",
    "no-promise-executor-return": "error",
    "no-self-compare": "error",
    "no-unmodified-loop-condition": "error",
    "no-unreachable-loop": "error",
    "no-unused-private-class-members": "error",
    "prefer-exponentiation-operator": ["error"],
    "prefer-const": "error",
    "require-await": "error",
    "symbol-description": ["error"],
    yoda: ["error", "never"],
    "vars-on-top": "error",
    "prefer-spread": "error",
    "prefer-rest-params": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-destructuring": "error",
    "prefer-arrow-callback": "error",
    "operator-assignment": "error",
    "no-void": "error",
    "no-useless-return": "error",
    "no-unneeded-ternary": "error",
    "no-undefined": "error",
    "no-undef-init": "error",
    "no-var": "error",
    "no-useless-constructor": "error",
  },
};
